"""Record the game's sound effects (G11).

Every effect in src/engine/sfxList.ts (via tools/sfx-list.ts) is generated by
ElevenLabs' sound generation from its prompt — a loop as a seamless loop — and
saved as public/audio/sfx/<id>.ogg: a loop cut where its own pattern repeats
best and crossfaded at the join (tools/seamless.py) at one constant gain, a
one-shot with its silence trimmed, both loudness-matched.
public/audio/sfx/manifest.json lists each file's prompt, length and loop;
only effects that are new or whose prompt, length or loop changed are
recorded (ElevenLabs charges per second: 40 credits a second).

Needs: Python 3.10+, ffmpeg on the PATH, Node (npx), and ELEVENLABS_API_KEY
in .env.local (git-ignored) — a key allowed Sound Effects. Sound effects work
on ElevenLabs' free plan (non-commercial, crediting ElevenLabs).
Run from the repository root:  python tools/make-sfx.py  [--all] [id ...]
  (--refinish: make loops recorded before the seamless step seamless, no credits)
"""
import json
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from seamless import make_seamless, fix_seam, level  # noqa: E402
from siren import build as build_siren  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'public' / 'audio' / 'sfx'
API = 'https://api.elevenlabs.io/v1/sound-generation?output_format=mp3_44100_128'


def api_key() -> str:
    env = ROOT / '.env.local'
    for line in (env.read_text('utf-8').splitlines() if env.exists() else []):
        if line.strip().startswith('ELEVENLABS_API_KEY='):
            return line.split('=', 1)[1].strip().strip('"').strip("'")
    sys.exit('ELEVENLABS_API_KEY is missing from .env.local')


def effects() -> dict:
    res = subprocess.run('npx tsx tools/sfx-list.ts', cwd=ROOT, shell=True, capture_output=True, check=True)
    return json.loads(res.stdout.decode('utf-8'))


def generate(key: str, d: dict, raw: Path) -> None:
    body = {'text': d['prompt'], 'duration_seconds': d['seconds'], 'prompt_influence': 0.5}
    if d['loop']:
        body['loop'] = True
    req = urllib.request.Request(API, method='POST', data=json.dumps(body).encode('utf-8'),
                                 headers={'xi-api-key': key, 'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=180) as r:
        raw.write_bytes(r.read())


def finish(d: dict, raw: Path, ogg: Path) -> None:
    if d['loop']:
        # a loop: only digital silence off the ends (the MP3 encoder's padding),
        # then cut where its own pattern repeats best and crossfade the join
        # (tools/seamless.py — a generated "loop" isn't reliably seamless),
        # at one constant gain
        with tempfile.TemporaryDirectory() as tmp:
            f32, cut = Path(tmp) / 'in.f32', Path(tmp) / 'loop.f32'
            subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', str(raw), '-af',
                            'silenceremove=start_periods=1:start_threshold=-90dB:start_silence=0,areverse,'
                            'silenceremove=start_periods=1:start_threshold=-90dB:start_silence=0,areverse',
                            '-ac', '1', '-ar', '44100', '-f', 'f32le', str(f32)], check=True)
            y, score = make_seamless(np.fromfile(f32, np.float32), 44100)
            level(fix_seam(y, 44100)).tofile(cut)
            encode_loop(cut, ogg)
        print(f'  seamless: {len(y) / 44100:.2f} s loop, pattern match {score:.2f}')
        return
    af = ('silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.02,areverse,'
          'silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.08,areverse,'
          'loudnorm=I=-18:TP=-1.5:linear=true')
    subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', str(raw), '-af', af, '-ac', '1', '-ar', '44100',
                    '-c:a', 'libvorbis', '-q:a', '5', str(ogg)], check=True)


def encode_loop(f32: Path, ogg: Path) -> None:
    """a loop's samples (44.1 kHz mono float) as OGG, untouched otherwise —
    no filter that isn't loop-aware may run over a loop"""
    subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-f', 'f32le', '-ar', '44100', '-ac', '1', '-i', str(f32),
                    '-c:a', 'libvorbis', '-q:a', '6', '-ar', '44100', str(ogg)], check=True)


def refinish(want: dict, manifest: dict) -> None:
    """make the loops recorded before the seamless step seamless, from their
    own files (no credits); each is done once (manifest '_seamless')"""
    done = set(manifest.get('_seamless', []))
    for sid, d in want.items():
        ogg = OUT / f'{sid}.ogg'
        if not d['loop'] or sid in done or not ogg.exists():
            continue
        with tempfile.TemporaryDirectory() as tmp:
            src = Path(tmp) / 'src.ogg'
            shutil.copy(ogg, src)
            print(f'{sid}.ogg')
            finish(d, src, ogg)
        done.add(sid)
    manifest['_seamless'] = sorted(done)


def main() -> None:
    redo = '--all' in sys.argv
    if '--refinish' in sys.argv:
        manifest_path = OUT / 'manifest.json'
        manifest = json.loads(manifest_path.read_text('utf-8'))
        refinish(effects(), manifest)
        manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', 'utf-8')
        return
    only = [a for a in sys.argv[1:] if not a.startswith('--')]
    OUT.mkdir(parents=True, exist_ok=True)
    manifest_path = OUT / 'manifest.json'
    old = json.loads(manifest_path.read_text('utf-8')) if manifest_path.exists() else {}
    want = effects()
    key = None
    manifest = {}
    seam = set(old.get('_seamless', []))
    for sid, d in want.items():
        ogg = OUT / f'{sid}.ogg'
        manifest[sid] = d
        fresh = old.get(sid) == d and ogg.exists()
        if fresh and not redo and (not only or sid not in only):
            continue
        if only and sid not in only:
            if ogg.exists() and sid in old:
                manifest[sid] = old[sid]
            continue
        if d.get('tones'):
            # a siren: built, sample-exactly periodic (no credits)
            t = d['tones']
            y = build_siren(t['lo'], t['hi'], t['tone'], t['cycles'])
            with tempfile.TemporaryDirectory() as tmp:
                f32 = Path(tmp) / 'siren.f32'
                level(y).tofile(f32)
                encode_loop(f32, ogg)
            print(f"{sid}.ogg  built siren {t['lo']}/{t['hi']} Hz, {t['tone']} s tones  (no credits)", flush=True)
            seam.add(sid)
            continue
        key = key or api_key()
        with tempfile.TemporaryDirectory() as tmp:
            raw = Path(tmp) / 'raw.mp3'
            generate(key, d, raw)
            finish(d, raw, ogg)
        print(f"{sid}.ogg  {d['seconds']}s{' loop' if d['loop'] else ''}  ({int(d['seconds'] * 40)} credits)", flush=True)
        if d['loop']:
            seam.add(sid)
    for f in OUT.glob('*.ogg'):
        if f.stem not in want:
            f.unlink()
            print(f'removed {f.name}')
    manifest['_seamless'] = sorted(seam & set(want))
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', 'utf-8')
    print(f'manifest: {manifest_path.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
